package millbuild

/** A generated file, path relative to the repo root.
  * Write = generated text; Copy = body file copied from source (preserves perms/exec bits). */
enum GenFile:
  case Write(path: os.SubPath, content: String)
  case Copy(path: os.SubPath, src: os.Path)

object Harness {
  val all: Seq[String] = Seq("claude", "codex", "cursor", "copilot", "windsurf", "devin")

  private val GEN_HEADER = "Generated by `mill skills.generateAll` — do not edit."

  /** Files this harness contributes for the given skill. Pure: no I/O beyond reading sources via resolvedBody (which returns paths). */
  def emit(id: String, m: SkillModel): Seq[GenFile] = id match {
    case "claude"   => claude(m, Codegen.resolvedBody(m.skillDir, "claude"))  // body = src/ + src-claude/
    case "cursor"   => cursor(m)
    case "copilot"  => copilot(m)
    case "windsurf" => windsurf(m)
    case "codex"    => agentsNeutral(m, Codegen.resolvedBody(m.skillDir, "")) // neutral body = src/ only
    case "devin"    => Seq.empty  // devin reads the neutral dist/agents/skills copy emitted for codex + AGENTS.md
    case other      => sys.error(s"unknown harness: $other")
  }

  private def claude(m: SkillModel, body: Seq[(os.SubPath, os.Path)]): Seq[GenFile] = {
    val base = os.sub / "dist" / "plugins" / m.id
    val pluginJson = GenFile.Write(
      base / ".claude-plugin" / "plugin.json",
      s"""{
         |  "$$schema": "https://json.schemastore.org/claude-code-plugin-manifest.json",
         |  "name": "${m.id}",
         |  "displayName": "${m.displayName}",
         |  "version": "${m.version}",
         |  "description": ${jsonStr(m.description)},
         |  "author": { "name": "${m.author}" },
         |  "license": "${m.license}",
         |  "keywords": ${jsonArr(m.tags)}
         |}
         |""".stripMargin
    )
    val files = body.map { case (rel, src) => GenFile.Copy(base / "skills" / m.id / rel, src) }
    // TODO: aggregate across skills when a second skill exists
    val marketplace = GenFile.Write(
      os.sub / ".claude-plugin" / "marketplace.json",
      s"""{
         |  "$$schema": "https://json.schemastore.org/claude-code-marketplace.json",
         |  "name": "squire",
         |  "description": "Eleven19's cross-harness skill marketplace.",
         |  "version": "0.1.0",
         |  "owner": { "name": "Eleven19", "url": "https://github.com/Eleven19" },
         |  "plugins": [
         |    {
         |      "name": "${m.id}",
         |      "source": "./dist/plugins/${m.id}",
         |      "description": ${jsonStr(m.description)},
         |      "author": { "name": "${m.author}" },
         |      "version": "${m.version}",
         |      "license": "${m.license}",
         |      "category": "${m.category}",
         |      "tags": ${jsonArr(m.tags)}
         |    }
         |  ]
         |}
         |""".stripMargin
    )
    marketplace +: pluginJson +: files
  }

  private def cursor(m: SkillModel): Seq[GenFile] = Seq(GenFile.Write(
    os.sub / "dist" / "cursor" / "rules" / s"${m.id}.mdc",
    s"""---
       |description: ${m.description}
       |alwaysApply: false
       |---
       |
       |<!-- $GEN_HEADER -->
       |
       |# ${m.id}
       |
       |Use the ${m.id} skill. Body + commands:
       |`dist/plugins/${m.id}/skills/${m.id}/SKILL.md`.
       |""".stripMargin
  ))

  private def copilot(m: SkillModel): Seq[GenFile] = Seq(
    GenFile.Write(os.sub / "dist" / "github" / "copilot-instructions.md",
      s"<!-- $GEN_HEADER -->\n\n# Copilot instructions\n\nSee `AGENTS.md`. Skill ${m.id}: ${m.description}\n"),
    GenFile.Write(os.sub / "dist" / "github" / "prompts" / s"${m.id}.prompt.md",
      s"---\ndescription: ${m.description}\nname: ${m.id}\n---\n\n<!-- $GEN_HEADER -->\n\nUse the ${m.id} skill: `dist/plugins/${m.id}/skills/${m.id}/SKILL.md`.\n")
  )

  private def windsurf(m: SkillModel): Seq[GenFile] = Seq(GenFile.Write(
    os.sub / "dist" / "windsurf" / "workflows" / s"${m.id}.md",
    s"---\ndescription: ${m.description}\n---\n\n<!-- $GEN_HEADER -->\n\n# ${m.id}\n\nUse the ${m.id} skill: `dist/plugins/${m.id}/skills/${m.id}/SKILL.md`.\n"
  ))

  private def agentsNeutral(m: SkillModel, body: Seq[(os.SubPath, os.Path)]): Seq[GenFile] =
    body.map { case (rel, src) => GenFile.Copy(os.sub / "dist" / "agents" / "skills" / m.id / rel, src) }

  private def jsonStr(s: String): String =
    "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", " ").trim + "\""
  private def jsonArr(xs: Seq[String]): String = xs.map(jsonStr).mkString("[", ", ", "]")
}
